apiVersion: 1

datasources:
  - name: ClickHouse-TJ
    type: grafana-clickhouse-datasource
    uid: clickhouse-tj
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: tj
      username: default
    secureJsonData:
      password: ""
